# Generated by Django 5.0 on 2024-01-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='student_name',
            new_name='answered_by',
        ),
    ]
