# Generated by Django 5.0 on 2024-01-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='quiz_for',
        ),
    ]
