# Generated by Django 5.0 on 2024-01-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='room_name',
            new_name='name',
        ),
    ]
