# Generated by Django 4.0.4 on 2023-04-05 15:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_visible', models.BooleanField()),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('select_multiple', models.BooleanField(null=True)),
                ('required', models.BooleanField(default=True)),
                ('correct_answer', models.TextField(null=True)),
                ('question_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizzes')),
            ],
        ),
    ]
