# Generated by Django 4.1.7 on 2023-03-23 11:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('questions', '0001_initial'), ('questions', '0002_question_select_multiple')]

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('visible', models.BooleanField()),
                ('choices', models.TextField(null=True)),
                ('correct_answer', models.TextField(null=True)),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('select_multiple', models.BooleanField(null=True)),
            ],
        ),
    ]
