# Generated by Django 4.0.4 on 2023-03-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='select_multiple',
            field=models.BooleanField(null=True),
        ),
    ]
