# Generated by Django 4.0.4 on 2023-04-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('mc', 'mc'), ('tf', 'tf'), ('sa', 'sa')], default='mc', max_length=255),
            preserve_default=False,
        ),
    ]
