# Generated by Django 5.0 on 2024-01-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_questions_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='correct_answer',
            new_name='correct_answers',
        ),
    ]
