name: Backend Lint

on:
    # Trigger the workflow on push or pull request,
    # but only for the base branch
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    ruff:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: cd backend
            - uses: chartboost/ruff-action@v1
